### ISSUE TITLE
Option to specify output cell size in A02 Site DEM prepare gives error if empty. 

### ISSUE THREAD

**Issue by hgrybas** [USDA-NRCS/HEL-Tools#27]
When running A03 Prepare Site DEM, the output cell size parameter is shown as optional. If you run the tool without this parameter, however, you receive an error message that it is missing.

![DEM setup](https://github.com/USDA-NRCS/HEL-Tools/assets/97195025/37168672-ebfd-4a4c-bed8-b02959e1503b)
![cell size error](https://github.com/USDA-NRCS/HEL-Tools/assets/97195025/72383cf6-ebbe-4073-b406-7b57caa609ff)

**Comment by dylan-harwell-usda** [comment]
This is because the Cell Size parameter is only visible if the chosen format is 'NRCS Image Service'. If you choose 'Local File' the Cell Size parameter is hidden, and having it required prevents the tool from running. It may be possible to dynamically make it required or optional in the validation code though.
![missing_required_param](https://github.com/USDA-NRCS/HEL-Tools/assets/120053864/f2677323-4f7d-42b4-9de2-37145e265144)

**Comment by DMillerAK** [comment]
Additionally, it seems like when you input the output cell size and then go to change the elevation units of the input DEM that it removes the number listed in the output cell size.  If you don't catch that removal, it will cause the error.

**Comment by dylan-harwell-usda** [comment]
I have also noticed that, and I believe it's because the tool validation code takes a while to execute, when it's figuring out the input/output coordinate systems and transformation list. The tool UI shows a little progressor bar near the top while the validation code is running, and I think if you enter a parameter before that finishes it wipes it out.

**Comment by dylan-harwell-usda** [comment]
Closing issue.

Through some research, the parameter type property of tool parameters is read-only and can't be changed dynamically. ESRI has a workaround to set an error message on an Optional parameter, but after some fiddling with that, it does not work as expected due to the validation code of this tool taking several seconds to execute. The solution is to wait for tool validation to complete before entering each parameter.
