### ISSUE TITLE
A03 Prepare DEM - CRS doesn't update to user specified option

### ISSUE THREAD

**Issue by KsmileyTN** [USDA-NRCS/HEL-Tools#28]
The prepare DEM tool appears to use the default CS of my map, but when I click the globe to change to another one, the tool does not initialize to the one I just chose. I changed it in the "environments" tab to see if it would override and it did. 

The CS that I wanted to change to is State Plane (2011) U.S. Feet. 

 I'm using 3.1.3

![image](https://github.com/USDA-NRCS/HEL-Tools/assets/87093085/bcdbde2e-58b8-4e33-bd71-6d14ef25dcfd)

**Comment by dylan-harwell-usda** [comment]
If I understand correctly, you attempted to change the Output Coordinate System? If so, this is by design, the requirement is for everything to be in a WGS84 UTM Zone for the Determination analysis. This is why the workflow has you first set your map frame to a UTM Zone before proceeding with anything else, and all subsequent layers created will be projected to the same UTM Zone as the map frame.

**Comment by KsmileyTN** [comment]
Thank you for the info. That makes sense.
