### ISSUE TITLE
HEL or NHEL letter created based on HEL present or not

### ISSUE THREAD

**Issue by RachelBolger** [USDA-NRCS/HEL-Tools#43]
Would like to see the HEL tool pick a template letter to create based on the HEL Present question in 03. Create letter and form tool, I would like the tool to create a different letter (.docx) based on if HEL is present or not.  I have created a template NHEL letter that will be created with the output documents (4 word docs created) when the tool is run but would like to have it only print/create the one letter based on yes or no value.
[Create_Forms_and_Letters.txt](https://github.com/USDA-NRCS/HEL-Tools/files/14390457/Create_Forms_and_Letters.txt)
[HEL_Yes_No.docx](https://github.com/USDA-NRCS/HEL-Tools/files/14390400/HEL_Yes_No.docx)
[NHELC_Letter_Template.docx](https://github.com/USDA-NRCS/HEL-Tools/files/14390408/NHELC_Letter_Template.docx)

**Comment by dylan-harwell-usda** [comment]
Will have to defer to @CEM-NRCS for any letter/form wording changes.

**Comment by CEM-NRCS** [comment]
Forwarding issue to Jason Outlaw and David Manthei for their review.

**Comment by CEM-NRCS** [comment]
Rachel, I got a response from David Manthei as follows:

_The template letter in the HEL Tool provides notification to the person and explains why a field may be labeled HEL or NHEL, and directs the person to the map, summary report, and 026-HELC for details/labels of field(s).  It then provides the required appeals information for preliminary AND final technical determinations (informal and formal appeals are provided simultaneously, so there could be instances, for example, where the person chooses to allow a decision to become final and then has the necessary information to exercise formal appeal rights if desired).  There doesn’t appear to be a need, therefore, to create multiple template letters. 

If a state wants to create a different version of the notification letter, dependent upon whether the determination is HEL vs. NHEL, that letter should go through some review prior to being used to ensure it meets all regulatory and policy requirements.  As written, the letter that NV sent as an example does not meet the requirements because it circumvents preliminary appeal rights, and I recommend they not use it._

David Manthei did say he is available to meet with you and compliance leads in your state to discuss options for an alternate letter, and review it, so if your team still wants to pursue this please reach out to David.

In the meantime, I will close this issue, but if your team comes up with an approved letter with David, we can then re-open this and start work on it. If that happens, please e-mail me at chris.morse@usda.gov so we can re-open it.
