### ISSUE TITLE
Using service for Frozen HEL soils

### ISSUE THREAD

**Issue by Navig8tor23** [USDA-NRCS/HEL-Tools#44]
I'm trying to use a statewide frozen HEL soils geodatabase on GIS-states and the tool is having issues with using the layer in 2 methods.
Toolbox has path to service pre-populated ---will not work.
HEL service is loaded into the map contents, and is used in that step.   no go.

However, if I use the 'browse folder' icon, and navigate to that HEL service layer, the tool will run and export out data.

service is at: https://gis-states.sc.egov.usda.gov/server/rest/services/Hosted/WI_Frozen_HEL_Soils_final/FeatureServer

I'll add Dylan to the group that I have setup here to be able to view\access that Frozen HEL layer.
![2024-02-26_13-24-49](https://github.com/USDA-NRCS/HEL-Tools/assets/154472530/4c36f551-3e35-419e-8304-e7b1824a4abf)

**Comment by dylan-harwell-usda** [comment]
Hey @Navig8tor23 thanks for the report. First thing I am curious about, what does the first error message say if you hover the X over the "Site Prepare HELC" field?

I'll try to reproduce on my end, thank you for sharing the soils layer with me.

**Comment by dylan-harwell-usda** [comment]
Ah yea, so the tool's validation runs after a parameter changed. So if you have no Fields selected, and then enter the Site Prepare HELC layer, the validation then fails and says you have no selected fields. If you select Fields after that, you have to change the parameter to trigger the validation again, i.e. the validation works when the parameter changes, it's not working off of you interacting with the layer after the parameter is set.

So best workflow is to 1) select your fields, 2) then enter the first parameter.

If you forgot to select fields before setting the Site Prepare HELC layer, then after you select fields, change that layer dropdown to something else, then change it back to Site Prepare HELC layer, this will get validation to pass.

I will look into the issue with the soils layer. My hunch, based on what you described, is it does not work with a path to the service because of the tool parameter Type, it's expecting a layer contained in the map, but I will confirm.

**Comment by dylan-harwell-usda** [comment]
https://github.com/USDA-NRCS/HEL-Tools/assets/120053864/a91b75b7-6426-4ec0-b5ef-f9840ed3bf86

Here is a screen recording of what I mean about triggering validation again post feature selection - pick any other layer, then pick the Site Prepare HELC layer again and it will be happy.

**Comment by dylan-harwell-usda** [comment]
@Navig8tor23 Did that resolve the issue with the service path?

**Comment by Navig8tor23** [comment]
Yep.      What was odd was that I used to browse icon in that toolbox to have that Frozen layer pre-populate that paramenter, and selected that Frozen HEL soils layer from within gis-states...

We're all good now.    Thanks again!
Craig
